// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiYeMbb6KcN8tT8OPOdgKZIV8qAIRt0U4',
    appId: '1:258933154699:web:2610d92534266149bb858e',
    messagingSenderId: '258933154699',
    projectId: 'mynotes-flutter-project-694eb',
    authDomain: 'mynotes-flutter-project-694eb.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-694eb.appspot.com',
    measurementId: 'G-QLGP6XQBHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LnC36V2eoCyrZ0I-4g0lVxCL2tmLPY4',
    appId: '1:258933154699:android:ae60850a517c1725bb858e',
    messagingSenderId: '258933154699',
    projectId: 'mynotes-flutter-project-694eb',
    storageBucket: 'mynotes-flutter-project-694eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDu51PNFvA6xdMOMA7CDRBieCli2-Byeg',
    appId: '1:258933154699:ios:d8581cc2fb27264dbb858e',
    messagingSenderId: '258933154699',
    projectId: 'mynotes-flutter-project-694eb',
    storageBucket: 'mynotes-flutter-project-694eb.appspot.com',
    iosClientId: '258933154699-ednrhq4a6u20p4froeavakdqverth2ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDu51PNFvA6xdMOMA7CDRBieCli2-Byeg',
    appId: '1:258933154699:ios:d8581cc2fb27264dbb858e',
    messagingSenderId: '258933154699',
    projectId: 'mynotes-flutter-project-694eb',
    storageBucket: 'mynotes-flutter-project-694eb.appspot.com',
    iosClientId: '258933154699-ednrhq4a6u20p4froeavakdqverth2ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
